const Data = [
  {
    // image: { img },
    projectName: "Project 1",
    projectInfo: "Rijan is know as lamkhuttey because of his height and body ",
    target: "2000",
    startdate: "2023-2-25",
    enddate: "2023-2-30",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectName: "Project 2",
    projectInfo: "Sandesh is a handsome guy who is very smart.",
    target: "100000",
    startdate: "2023-2-25",
    enddate: "2023-2-31",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectName: "Project 3",
    projectInfo: "Saksham is Farsi which is also known as vegetable.",
    target: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-29",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectName: "Project 4",
    projectInfo: "Saksham is Farsi which is also known as vegetable.",
    target: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-30",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectName: "Project 5",
    projectInfo: "Saksham is Farsi which is also known as vegetable.",
    target: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-31",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectName: "Project 6",
    projectInfo: "Saksham is Farsi which is also known as vegetable.",
    target: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-29",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
];
export default Data;
