const Data = [
  {
    // image: { img },
    projectname: "Project 1",
    description: "Rijan is know as lamkhuttey because of his height and body ",
    amount: "2000",
    startdate: "2023-2-25",
    enddate: "2023-2-30",
    beneficiaries: [{ email: "sandesh", username: "san1" }],
  },
  {
    // image: { img },
    projectname: "Project 2",
    description: "Sandesh is a handsome guy who is very smart.",
    amount: "100000",
    startdate: "2023-2-25",
    enddate: "2023-2-31",
  },
  {
    // image: { img },
    projectname: "Project 3",
    description: "Saksham is Farsi which is also known as vegetable.",
    amount: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-29",
  },
  {
    // image: { img },
    projectname: "Project 4",
    description: "Saksham is Farsi which is also known as vegetable.",
    amount: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-30",
  },
  {
    // image: { img },
    projectname: "Project 5",
    description: "Saksham is Farsi which is also known as vegetable.",
    amount: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-31",
  },
  {
    // image: { img },
    projectname: "Project 6",
    description: "Saksham is Farsi which is also known as vegetable.",
    amount: "5000",
    startdate: "2023-2-25",
    enddate: "2023-2-29",
  },
];
export default Data;
